---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: ru
dictionaryDefinitions:
  - name: project-words
    path: './cspell-custom-words.txt'
    addWords: true
dictionaries:
  - project-words
ignorePaths:
  - 'node_modules'
  - '/cspell-custom-words.txt'
